set(tools C:/UnrealToolchains/v19_clang-11.0.1-centos7/x86_64-unknown-linux-gnu)
set(CMAKE_C_COMPILER ${tools}/bin/clang.exe)
set(CMAKE_CXX_COMPILER ${tools}/bin/clang++.exe)
set(CMAKE_AR ${tools}/bin/llvm-ar.exe)
set(CMAKE_LINKER ${tools}/bin/ld.lld.exe)
set(CMAKE_STRIP ${tools}/bin/x86_64-unknown-linux-gnu-strip.exe)
set(CMAKE_NM ${tools}/bin/x86_64-unknown-linux-gnu-nm.exe)
set(CMAKE_OBJCOPY ${tools}/bin/x86_64-unknown-linux-gnu-objcopy.exe)
set(CMAKE_OBJDUMP ${tools}/bin/x86_64-unknown-linux-gnu-objdump.exe)
#set(RUN_HAVE_STD_REGEX 0)
#set(RUN_HAVE_POSIX_REGEX 0)
#set(_gRPC_CPP_PLUGIN C:/Users/utente/Documents/EasyGrpc/protobuf/win64/grpc_cpp_plugin.exe)
#set(_gRPC_PROTOBUF_PROTOC C:/Users/utente/Documents/EasyGrpc/protobuf/win64/protoc.exe)
#set(CMAKE_CXX_LINK_EXECUTABLE ${tools}/bin/lldb.exe)
#set(CMAKE_C_LINK_EXECUTABLE ${tools}/bin/lldb.exe)
set(CMAKE_THREAD_LIBS_INIT "-lpthread")
#set(CMAKE_HAVE_THREADS_LIBRARY 1)
#set(CMAKE_USE_WIN32_THREADS_INIT 0)
#set(CMAKE_USE_PTHREADS_INIT 1)
#set(THREADS_PREFER_PTHREAD_FLAG ON)
#set (CMAKE_THREAD_LIBS_INIT C:/UnrealToolchains/v19_clang-11.0.1-centos7/x86_64-unknown-linux-gnu/lib64/libpthread.so.0)
include_directories(C:/UnrealToolchains/v19_clang-11.0.1-centos7/x86_64-unknown-linux-gnu/include)


set(PROJECT_SOURCE_DIR C:/Users/utente/Documents/EasyGrpc/grpcsource)
set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
#set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(RUN_HAVE_STD_REGEX 0)
set(RUN_HAVE_POSIX_REGEX 0)

#set(CMAKE_INSTALL_LIBDIR C:/Users/utente/Documents/EasyGrpc/grpcsource/cmake/build/libout)

set(CMAKE_SYSTEM_PROCESSOR "x86_64")
set(CPACK_PACKAGE_ARCHITECTURE "x86_64")
set(CMAKE_SYSTEM_NAME "Linux")
set(OPENSSL_ROOT_DIR C:/Users/utente/Documents/EasyGrpc/grpcsource/OpenSSL/*)