set(ZLIB_ROOT ${SOURCE_DIR}/ZLib/${THIRD_PARTY_ARCHITECTURE}/*)
set(OPENSSL_ROOT_DIR ${SOURCE_DIR}/OpenSSL/${THIRD_PARTY_ARCHITECTURE}/*)

message(STATUS "OPENSSL_ROOT_DIR: ${SOURCE_DIR}/OpenSSL/${THIRD_PARTY_ARCHITECTURE}/")
message(STATUS "ZLIB_ROOT: ${SOURCE_DIR}/ZLib/${THIRD_PARTY_ARCHITECTURE}/")